### ISSUE TITLE
Fix CI failure

### ISSUE THREAD

**Issue by shayanh** [DistCompiler/pgo#217]
I believe CI failures are due to two problems in the tcp mailboxes that I describe them below.

1. Receiving duplicate commit messages causes negative wait group count and a panic consequently. This issue happened exactly after we decreased send timeout value.

2. If a remote tcp mailbox aborts after sending precommit causes the receiving side to get blocked forever and it cannot gets closed.

**Comment by fhackett** [comment]
This is done now, closing. (see above, it just didn't reflect in the issues list)
