### ISSUE TITLE
Support TLC module `ToString` Operator

### ISSUE THREAD

**Issue by shayanh** [DistCompiler/pgo#229]
TLC module has a `ToString` operator that converts an input to string. Currently, it's not possible to use this in an MPCal spec.

**Comment by fhackett** [comment]
Can you include a link to where this operator is documented / specified? I'd like to attach it to the correct import, etc...

**Comment by shayanh** [comment]
https://github.com/tlaplus/tlaplus/blob/master/tlatools/org.lamport.tlatools/src/tla2sany/StandardModules/TLC.tla#L121
