### ISSUE TITLE
Complete documentation for gogen

### ISSUE THREAD

**Issue by Lzyabc** [DistCompiler/pgo#248]
I've been using your tool and find it very helpful. However, I noticed that the documentation for the gogen is incomplete.  For example, the method to bootstrap the generated go implementation.  Can you provide complete documentation for gogen with some examples?

**Comment by fhackett** [comment]
Hi - thanks for your question.

You can find a smaller fully worked Modular PlusCal + Go example here: https://github.com/DistCompiler/pgo/blob/main/systems/loadbalancer/

The tests in that folder are one example of how to use the gogen output. Look specifically at `distsys.NewMPCalContext` and how it is used. The functions in `distsys` are documented using the standard Go docs format, and there should be descriptions for many of the common components. Do let us know if there's something unclear there.

I've also made a request for online Go docs, which should be available here eventually: https://pkg.go.dev/github.com/DistCompiler/pgo/distsys

**Comment by Lzyabc** [comment]
Thanks! I can run the examples now.

**Comment by fhackett** [comment]
Closing for now - reopen or make a new issue if you run into any trouble.
